tasks:
  - init: |
      echo 'Installing selenium'
      pip3 install selenium
      brew install rbenv
      brew install aws-okta
      brew install awscli
      brew install dnsmasq
    command: |
      python redfinscraper.py